region="us-east-1"
api_stage_name="test"
environment_tag="Test Lambda Example"
lamda_role_name="TestLambdaRole"
lambda_s3_policy_name="TestLambdaS3Policy"
function_name="test_lambda_function"
handler="lambda.handler"
runtime="python3.6"
